
[workspace]
members = [
    "code/called",
    "code/caller",
    "tests"
]

resolver = "2"

[workspace.dependencies]
solana-program = "2.2.0"
solana-sdk = "2.2.0"
solana-client = "2.2.0"
tokio = "1.37"
solana-transaction-status = "2.3.13"

